### ISSUE TITLE
KeyError: '33338203782'

### ISSUE THREAD

**Issue by cgnerds** [wentaozhu/AutoShot#1]
There are several problems, and I solved some by myself.
(1) In utils.py line 49, I changed the font to a local font, like '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf';
(2) I copyed transnetv2.py from https://github.com/soCzech/TransNetV2/tree/master/inference;
But then I found the errors as follows:
![image](https://user-images.githubusercontent.com/3292333/232044142-bba5eef6-b3a6-4337-8c1a-0da7095d2d6d.png)
Can you kindly tell me how to solve it? Thank you very much!

**Comment by wentaozhu** [comment]
Did you work on step 5 and step 6? Thank you so much!

Step 5: Download baseline model using link (https://pan.baidu.com/s/1CdCVNzFdF3U6I4ajfejYNQ?pwd=sfkq passcode: sfkq), and move the model ckpt_0_200_0.pth to this directory.

Step 6: Download baseline existing prediction using link (https://pan.baidu.com/s/1CdCVNzFdF3U6I4ajfejYNQ?pwd=sfkq passcode: sfkq), and move the prediction baseline_one_hot_pred_dict_baseline.pickle and gt_scenes_dict_baseline_v2.pickle to this directory

**Comment by cgnerds** [comment]
Yes, the file 33338203782.mp4 is in the  folder. By the way, there are two step3.

**Comment by wentaozhu** [comment]
If so, the dictionary should have this file. I will check this tomorrow. Thank you so much!

**Comment by wentaozhu** [comment]
Could you please check the number of keys in `fnm_path_dict` by `print(len(fnm_path_dict.keys()))` in line 30? If the number of keys is less than the number of mp4 files, around 800, the line 21 to 30 might be inaccurate. There might be some files not being included in the dict `fnm_path_dict`. Thank you so much!

**Comment by wentaozhu** [comment]
You can also follow Google Drive Google Drive: https://drive.google.com/drive/folders/1xZN6tvefXXmpZlIZ6GoSUUxpDQQOSNfJ?usp=sharing  to download the data. Thank you!
